### ISSUE TITLE
Names and photos.

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [Royal-Modding/FS19_CallContractors#5]
![fsScreen_2021_04_09_20_22_15](https://user-images.githubusercontent.com/8200153/114219157-fa530b80-9972-11eb-911d-8b54fed590c2.png)
![fsScreen_2021_04_09_20_21_51](https://user-images.githubusercontent.com/8200153/114219159-fb843880-9972-11eb-9aef-939f0f319666.png)
Thanks for the mod guys!
My remark only refers to the aesthetic form.
Sometimes the names of the boys belong to girls and on the contrary.
And sometimes the same photos for different people.

**Comment by TyKonKet** [comment]
Hi @Gonimy-Vetrom thank you so much for your feedback.
 - The issue with same photo for different NPC have been fixed with last commit.
 - The issue with names cannot be fixed since NPC are defined by mappers, most of the time they use default NPC defined by GIANTS and probably the error comes from them.
